---
title: "Plots Paper Lnuclei"
output: html_notebook
---


```{r}
library(umap)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(rlist)
library(patchwork)
library(pheatmap)
library(ggplotify)
```

```{r}
data_Lnuclei = read.csv("final_mean_meth_region_Lnuclei_CpGIs.tsv", sep = "\t")
cluster_Lnuclei = read.csv("cluster_posteriors_bestrun_region_Lnuclei.tsv", sep = "\t")
```

```{r}
colnames(cluster_Lnuclei)[2:3] = 1:2
cluster_Lnuclei$cluster = colnames(cluster_Lnuclei[2:3])[apply(cluster_Lnuclei[2:3],1,which.max)]

data_Lnuclei[is.na(data_Lnuclei)] = 0
data_Lnuclei = as.data.frame(t(data_Lnuclei))
rownames(data_Lnuclei) = gsub("[.]", "-", rownames(data_Lnuclei))
data_Lnuclei = data_Lnuclei[rownames(data_Lnuclei) %in% cluster_Lnuclei$cell_id,]
```

```{r}
umap_Lnuclei = umap(data_Lnuclei)
head(umap_Lnuclei$layout)
```

```{r}
plot_Lnuclei = data.frame(x = umap_Lnuclei$layout[,1], y = umap_Lnuclei$layout[,2], cell_id = rownames(umap_Lnuclei$layout))
plot_Lnuclei = merge(plot_Lnuclei, cluster_Lnuclei[c("cell_id", "cluster")], by = "cell_id")
plot_Lnuclei$pool = unlist(strsplit(plot_Lnuclei$cell_id, split = '-') %>% list.map(.[2]))

plot_Lnuclei$batch = "1"
plot_Lnuclei[plot_Lnuclei$pool %in% c("pool76", "pool77", "pool78", "pool79", "pool80", "pool81"),]$batch = "2"
plot_Lnuclei[plot_Lnuclei$pool %in% c("pool82", "pool83", "pool84", "pool85", "pool86", "pool87"),]$batch = "3"
```

```{r}
A = ggplot(plot_Lnuclei, aes()) + 
  geom_point(aes(x=x, y=y, color=cluster), size = 2.5, show.legend = F) +
  scale_colour_manual(values = c("orange", "green4")) +
  xlab("umap 1") +
  ylab("umap 2") +
  theme_bw() +
  ggtitle("") +
   theme(axis.title = element_text(size = 15), 
         axis.text = element_text(size = 15))
```

```{r}
B = ggplot(plot_Lnuclei, aes()) + 
  geom_point(aes(x=x, y=y, color=pool), size = 2.5, show.legend = F) +
  xlab("umap 1") +
  ylab("umap 2") +
  ggtitle("") +
  theme_bw() + 
  theme(axis.title = element_text(size = 15), 
         axis.text = element_text(size = 15))
```

```{r}
C = ggplot(plot_Lnuclei, aes()) + 
  geom_point(aes(x=x, y=y, color=batch, shape = batch), size = 2.5, alpha = 0.8,  show.legend = F) +
  scale_color_manual(values = c("red3", "royalblue3", "green4")) +
  xlab("umap 1") +
  ylab("umap 2") +
  theme_bw() +
  theme(axis.title = element_text(size = 15), 
         axis.text = element_text(size = 15))

```

```{r}
matrix = as.matrix(data_Lnuclei[cluster_Lnuclei[order(cluster_Lnuclei$cluster),]$cell_id,])

row_an = as.data.frame(cluster_Lnuclei[order(cluster_Lnuclei$cluster),]$cluster)
rownames(row_an) = cluster_Lnuclei[order(cluster_Lnuclei$cluster),]$cell_id
colnames(row_an) = "cluster"

row_color = list(cluster = c("1" = "orange", "2" = "green4"))
```


```{r}
D = as.ggplot(pheatmap(matrix, 
         cluster_rows = F, 
         show_rownames = F, 
         show_colnames = F, 
         annotation_legend = F,
         annotation_names_row = F,
         treeheight_col = 25, 
         gaps_row = 0, 
         annotation_row = row_an, 
         annotation_colors = row_color), 
         )

```

```{r}
cluster = A + D
ggsave(plot = cluster, filename = "Lnuclei_plot_cluster.pdf", width = 30, units = "cm")
cluster 
```


```{r}
batch = B + C
ggsave(plot = batch, filename = "Lnuclei_plot_batch.pdf", width = 30, units = "cm")
batch
```

```{r}
pres = (A + D) / (B + C)
pres
ggsave(plot = pres, filename = "Lnuclei_plot_pres.jpeg", width = 20, units = "cm")
```

