---
title: "Lnuclei Custers" 
output: html_notebook
---

```{r}
GB = read.csv("cluster_posteriors_bestrun_region_Lnuclei_GB.tsv", sep = "\t")
CpG_Is = read.csv("cluster_posteriors_bestrun_region_Lnuclei_CpGIs.tsv", sep = "\t")
TSS = read.csv("cluster_posteriors_bestrun_region_Lnuclei_TSS.tsv", sep = "\t")
```

```{r}
colnames(GB)[2:3] = 1:2
GB$cluster = colnames(GB[2:3])[apply(GB[2:3],1,which.max)]

colnames(CpG_Is)[2:3] = 1:2
CpG_Is$cluster = colnames(CpG_Is[2:3])[apply(CpG_Is[2:3],1,which.max)]

colnames(TSS)[2:3] = 1:2
TSS$cluster = colnames(TSS[2:3])[apply(TSS[2:3],1,which.max)]
```

```{r}
clusters = merge(TSS[c("cell_id", "cluster")], GB[c("cell_id", "cluster")], by = "cell_id", suffixes = c(".TSS", ".GB"))
clusters = merge(clusters, CpG_Is[c("cell_id", "cluster")], by = "cell_id")
colnames(clusters)[4] = "cluster.CpG_Is"
```

```{r}
clusters = clusters[order(clusters$cluster.CpG_Is),]
rownames(clusters) = clusters$cell_id
clusters$cluster.TSS = as.numeric(clusters$cluster.TSS)
clusters$cluster.GB = as.numeric(clusters$cluster.GB)
clusters$cluster.CpG_Is = as.numeric(clusters$cluster.CpG_Is)

clusters$new.CpG_Is = 1
clusters[clusters$cluster.CpG_Is == 1,]$new.CpG_Is = 2
clusters = clusters[,-4]
colnames(clusters)[4] = "cluster.CpG_Is"
```

```{r}
colnames(clusters) =c("cell_id", "TSS", "Gene Bodies", "CpG Islands")
```


```{r}
m = as.matrix(clusters[,2:4])
heatmap(t(m), Rowv	= NA, Colv = NA,)
```

```{r}
clusters
```

```{r}
write.csv(clusters, sep = ",", row.names = F, file = "Lnclei_Cluster_Epiclomal.csv")
```

